ROUTE_MAPPING = {
    "About.md": "/about",
    "privacy_policy.md": "/privacy-policy", 
    "refund_policy.md": "/refund-policy",
    "terms_and_conditions.md": "/terms-and-conditions",
    "marketing_policy.md": "/marketing-policy",
    "cookie_policy.md": "/cookie-policy",
    "support.md": "/support",
    "reMIDI_4_installation_instructions.md": "/remidi-4-installation",
    "reMIDI_4_user_manual.md": "/user-manuals/remidi-4-user-manual",
    "remidi4copy.md": "/products/remidi-4",
    "rechannelcopy.md": "/products/rechannel",
    "sampleloops1copy.md": "/products/sw-select-sample-loops-vol-1",
    "sampleloops2copy.md": "/products/sw-select-sample-loops-vol-2",
    "jazzcompletecopy.md": "/products/sw-jazz-complete-volumes-1-11",
    "songwish_landing_page.md": "/",
}

def get_all_route_mappings():
    return {
        "/": "Home page with product showcase and features",
        "/about": "About SongWish company and team information", 
        "/support": "Customer support and help center",
        "/products": "All products overview page",
        "/products/plugins": "Audio plugins category page",
        "/products/sample-packs": "Sample packs category page", 
        "/products/free-downloads": "Free downloads and trials",
        "/products/deals": "Current deals and promotions",
        "/products/remidi-4": "reMIDI 4 MIDI plugin details and purchase",
        "/products/rechannel": "ReChannel audio plugin details",
        "/products/sw-select-sample-loops-vol-1": "Sample Loops Volume 1 pack",
        "/products/sw-select-sample-loops-vol-2": "Sample Loops Volume 2 pack", 
        "/products/sw-jazz-complete-volumes-1-11": "Complete Jazz sample collection",
        "/account": "User account dashboard (requires login)",
        "/user-manuals": "User manuals and documentation hub",
        "/user-manuals/remidi-4-user-manual": "Complete reMIDI 4 user manual",
        "/remidi-4-installation": "reMIDI 4 installation guide",
        "/privacy-policy": "Privacy policy and data handling",
        "/refund-policy": "Refund and return policy", 
        "/terms-and-conditions": "Terms of service and conditions",
        "/marketing-policy": "Marketing and communication policy",
        "/cookie-policy": "Cookie usage and consent policy",
        "/checkout": "Product purchase and payment page",
        "/products/purchase-success": "Order confirmation page"
    }
